#!/usr/bin/env node
/**
 * Writes `config.js` from env vars at build time.
 *
 * `config.js` is gitignored (it's the local-runtime Supabase config), so on
 * Vercel — where there is no committed `config.js` — we materialize one from
 * the project's environment variables. Missing values fall through to empty
 * strings, which keeps the app in its localStorage-only mode.
 *
 * Vars honored (first non-empty wins):
 *   SUPABASE_URL, NEXT_PUBLIC_SUPABASE_URL, VITE_SUPABASE_URL
 *   SUPABASE_ANON_KEY, NEXT_PUBLIC_SUPABASE_ANON_KEY, VITE_SUPABASE_ANON_KEY
 */
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const target = resolve(root, 'config.js');

const pick = (...names) => {
  for (const n of names) {
    const v = process.env[n];
    if (v && v.trim()) return v.trim();
  }
  return '';
};

const url = pick('SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL', 'VITE_SUPABASE_URL');
const key = pick(
  'SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'VITE_SUPABASE_ANON_KEY',
);

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const banner = `/* Generated by scripts/build-config.mjs at build time. Do not edit. */`;
const body = `window.SUPABASE_URL = '${esc(url)}';\nwindow.SUPABASE_ANON_KEY = '${esc(key)}';\n`;
const out = `${banner}\n${body}`;

if (existsSync(target)) {
  const existing = readFileSync(target, 'utf8');
  if (!existing.includes('Generated by scripts/build-config.mjs')) {
    if (!url && !key) {
      console.log('[build-config] no env vars set, leaving existing config.js untouched');
      process.exit(0);
    }
    console.log('[build-config] overwriting existing config.js from env vars');
  }
}

writeFileSync(target, out, 'utf8');
const mask = (s) => (s ? `${s.slice(0, 6)}…(${s.length} chars)` : '(empty)');
console.log(`[build-config] wrote config.js  url=${mask(url)}  key=${mask(key)}`);
